/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace MatchRegistry {
  export type MatchProposalStruct = {
    userA: AddressLike;
    userB: AddressLike;
    aiScoreHash: BytesLike;
    metadataHash: BytesLike;
    createdAt: BigNumberish;
    deadline: BigNumberish;
    yesVotes: BigNumberish;
    noVotes: BigNumberish;
    status: BigNumberish;
  };

  export type MatchProposalStructOutput = [
    userA: string,
    userB: string,
    aiScoreHash: string,
    metadataHash: string,
    createdAt: bigint,
    deadline: bigint,
    yesVotes: bigint,
    noVotes: bigint,
    status: bigint
  ] & {
    userA: string;
    userB: string;
    aiScoreHash: string;
    metadataHash: string;
    createdAt: bigint;
    deadline: bigint;
    yesVotes: bigint;
    noVotes: bigint;
    status: bigint;
  };
}

export interface MatchRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "canVote"
      | "daoToken"
      | "finalize"
      | "getProposal"
      | "hasVoted"
      | "isMatchApproved"
      | "noThreshold"
      | "proposalCount"
      | "proposals"
      | "proposeMatch"
      | "vote"
      | "voteDurationSeconds"
      | "yesThreshold"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "MatchFinalized" | "MatchProposed" | "Voted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "canVote",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "daoToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "finalize",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasVoted",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isMatchApproved",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "noThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proposalCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proposals",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeMatch",
    values: [AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vote",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "voteDurationSeconds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "yesThreshold",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "canVote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "daoToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "finalize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasVoted", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isMatchApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "noThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposalCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "proposals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proposeMatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "voteDurationSeconds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "yesThreshold",
    data: BytesLike
  ): Result;
}

export namespace MatchFinalizedEvent {
  export type InputTuple = [matchId: BigNumberish, status: BigNumberish];
  export type OutputTuple = [matchId: bigint, status: bigint];
  export interface OutputObject {
    matchId: bigint;
    status: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchProposedEvent {
  export type InputTuple = [
    matchId: BigNumberish,
    userA: AddressLike,
    userB: AddressLike,
    aiScoreHash: BytesLike,
    metadataHash: BytesLike,
    deadline: BigNumberish
  ];
  export type OutputTuple = [
    matchId: bigint,
    userA: string,
    userB: string,
    aiScoreHash: string,
    metadataHash: string,
    deadline: bigint
  ];
  export interface OutputObject {
    matchId: bigint;
    userA: string;
    userB: string;
    aiScoreHash: string;
    metadataHash: string;
    deadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VotedEvent {
  export type InputTuple = [
    matchId: BigNumberish,
    voter: AddressLike,
    support: boolean,
    yesVotes: BigNumberish,
    noVotes: BigNumberish
  ];
  export type OutputTuple = [
    matchId: bigint,
    voter: string,
    support: boolean,
    yesVotes: bigint,
    noVotes: bigint
  ];
  export interface OutputObject {
    matchId: bigint;
    voter: string;
    support: boolean;
    yesVotes: bigint;
    noVotes: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MatchRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): MatchRegistry;
  waitForDeployment(): Promise<this>;

  interface: MatchRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  canVote: TypedContractMethod<
    [matchId: BigNumberish, voter: AddressLike],
    [boolean],
    "view"
  >;

  daoToken: TypedContractMethod<[], [string], "view">;

  finalize: TypedContractMethod<[matchId: BigNumberish], [void], "nonpayable">;

  getProposal: TypedContractMethod<
    [matchId: BigNumberish],
    [MatchRegistry.MatchProposalStructOutput],
    "view"
  >;

  hasVoted: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  isMatchApproved: TypedContractMethod<
    [matchId: BigNumberish],
    [boolean],
    "view"
  >;

  noThreshold: TypedContractMethod<[], [bigint], "view">;

  proposalCount: TypedContractMethod<[], [bigint], "view">;

  proposals: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        userA: string;
        userB: string;
        aiScoreHash: string;
        metadataHash: string;
        createdAt: bigint;
        deadline: bigint;
        yesVotes: bigint;
        noVotes: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  proposeMatch: TypedContractMethod<
    [userB: AddressLike, aiScoreHash: BytesLike, metadataHash: BytesLike],
    [bigint],
    "nonpayable"
  >;

  vote: TypedContractMethod<
    [matchId: BigNumberish, support: boolean],
    [void],
    "nonpayable"
  >;

  voteDurationSeconds: TypedContractMethod<[], [bigint], "view">;

  yesThreshold: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "canVote"
  ): TypedContractMethod<
    [matchId: BigNumberish, voter: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "daoToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "finalize"
  ): TypedContractMethod<[matchId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getProposal"
  ): TypedContractMethod<
    [matchId: BigNumberish],
    [MatchRegistry.MatchProposalStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasVoted"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isMatchApproved"
  ): TypedContractMethod<[matchId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "noThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "proposalCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "proposals"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        userA: string;
        userB: string;
        aiScoreHash: string;
        metadataHash: string;
        createdAt: bigint;
        deadline: bigint;
        yesVotes: bigint;
        noVotes: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "proposeMatch"
  ): TypedContractMethod<
    [userB: AddressLike, aiScoreHash: BytesLike, metadataHash: BytesLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "vote"
  ): TypedContractMethod<
    [matchId: BigNumberish, support: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "voteDurationSeconds"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "yesThreshold"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "MatchFinalized"
  ): TypedContractEvent<
    MatchFinalizedEvent.InputTuple,
    MatchFinalizedEvent.OutputTuple,
    MatchFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "MatchProposed"
  ): TypedContractEvent<
    MatchProposedEvent.InputTuple,
    MatchProposedEvent.OutputTuple,
    MatchProposedEvent.OutputObject
  >;
  getEvent(
    key: "Voted"
  ): TypedContractEvent<
    VotedEvent.InputTuple,
    VotedEvent.OutputTuple,
    VotedEvent.OutputObject
  >;

  filters: {
    "MatchFinalized(uint256,uint8)": TypedContractEvent<
      MatchFinalizedEvent.InputTuple,
      MatchFinalizedEvent.OutputTuple,
      MatchFinalizedEvent.OutputObject
    >;
    MatchFinalized: TypedContractEvent<
      MatchFinalizedEvent.InputTuple,
      MatchFinalizedEvent.OutputTuple,
      MatchFinalizedEvent.OutputObject
    >;

    "MatchProposed(uint256,address,address,bytes32,bytes32,uint64)": TypedContractEvent<
      MatchProposedEvent.InputTuple,
      MatchProposedEvent.OutputTuple,
      MatchProposedEvent.OutputObject
    >;
    MatchProposed: TypedContractEvent<
      MatchProposedEvent.InputTuple,
      MatchProposedEvent.OutputTuple,
      MatchProposedEvent.OutputObject
    >;

    "Voted(uint256,address,bool,uint32,uint32)": TypedContractEvent<
      VotedEvent.InputTuple,
      VotedEvent.OutputTuple,
      VotedEvent.OutputObject
    >;
    Voted: TypedContractEvent<
      VotedEvent.InputTuple,
      VotedEvent.OutputTuple,
      VotedEvent.OutputObject
    >;
  };
}
