/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as matchRegistrySol from "./MatchRegistry.sol";
export { DemoDAOToken__factory } from "./DemoDAOToken__factory";
