/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as matchRegistrySol from "./MatchRegistry.sol";
export type { matchRegistrySol };
export type { DemoDAOToken } from "./DemoDAOToken";
export * as factories from "./factories";
export { DemoDAOToken__factory } from "./factories/DemoDAOToken__factory";
export type { IERC20 } from "./MatchRegistry.sol/IERC20";
export { IERC20__factory } from "./factories/MatchRegistry.sol/IERC20__factory";
export type { MatchRegistry } from "./MatchRegistry.sol/MatchRegistry";
export { MatchRegistry__factory } from "./factories/MatchRegistry.sol/MatchRegistry__factory";
